### ISSUE TITLE
cool project!

### ISSUE THREAD

**Issue by aquynh** [binarybird/Disassemble#1]
hi, this looks like a very cool project! but how about renaming it to something more unique? i think "Disassemble" is a bit too generic.

keep it up, cheers

**Comment by binarybird** [comment]
Thanks!
Yeah, its current title is pretty uninspired, Ill get it a real name eventually

**Comment by binarybird** [comment]
AAnnnd named.

**Comment by aquynh** [comment]
great, linked to your project from our website now: http://www.capstone-engine.org/showcase.html

cheers.

**Comment by aquynh** [comment]
i dont want to open a new issue, so sorry to post it here.

we got a proposal to change Java binding for Maven here: https://github.com/aquynh/capstone/pull/609
it might affect Redress, so would you mind reviewing it?

thanks.
